#!/usr/bin/with-contenv bash

# check if ssh directory exists in config
[[ ! -d /config/ssh ]] && mv /etc/ssh /config/ssh 

# remove /etc/ssh folder to allow us to symbolic link
[[ -d /etc/ssh ]] && rm -rf /etc/ssh

# symbolic link ssh and config
/bin/ln -s /config/ssh /etc/ssh

# generate key files
[[ ! -f /etc/ssh/ssh_host_rsa_key ]] && ssh-keygen -A

# add backup user
#/usr/sbin/adduser -h /home/rssh/ -s /usr/bin/rssh rssh -D 
/usr/sbin/useradd -m -d /home/rssh/ -s /usr/bin/rssh rssh
/usr/bin/passwd -d rssh

# generate .ssh folder
[[ ! -d /home/rssh/.ssh ]] && \
    mkdir /home/rssh/.ssh

[[ ! -f /config/authorized_keys ]] && echo "generating auth keys" && touch /config/authorized_keys
/bin/cp /config/authorized_keys /home/rssh/.ssh/

#always fix permissions at boot
chown rssh:rssh -R /home/rssh
chmod 700 -R /home/rssh/
chmod 600 -R /home/rssh/.ssh/authorized_keys

# place rssh config file
[[ ! -f /config/rssh.conf ]] && cp /defaults/rssh.conf /config/

# symbolic link rssh.conf
/bin/ln -s /config/rssh.conf /etc/rssh.conf

# permissions
chown abc:abc -R \
	/config
